export class GovernmentAnimalRegistration {
    nlhd_Number:string;
    owner_name:string;
    owner_village:string;
    owner_gewog:string;
    owner_dzongkhag:string;
    animalRegistrationNumber:String;
    damNumber:String;
    damExotic:number;
    damName:String;
    sireNumber:String;
    sireName:String;
    sireExotic:number;
    housing_type_option:String;
    animalname:String;
    mobile_number:String;
    birthdate:Date;
    animalAge:number;
    migration:String;
    migrationRegion:String;
    sex:string;
    category:string;
    bcs:number;
    damBreed:string;
    damBreedId:number;
    sireBreed:string;
    sireBreedId:number;
    CHBPP:String;
    animalBreedType:number;
    animalExotic:number;
}

